### ISSUE TITLE
Create `.unitypackage` 

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus-unity3d#101]
By having an `.unitypackage` file users can download the sources & install more easily by double-clicking the `.unitypackage` and installing without the need to copy the client files into their project manually

**Comment by rnd256** [comment]
Does double-clicking a `.unitypackage` support auto-deleting the old version of a package in your Unity project before importing the newer version? If so, that would be handy for upgrades.

**Comment by rthery** [comment]
@rnd256 No it doesn't, when upgrading with a `.unitypackage` you need to remove the previous folders and then import the new package to be sure to remove any deleted files in the new version.

That way of distributing packages is not recommended anymore, it would be better to distribute it through the Unity Package Manager, as described here:
https://docs.unity3d.com/Manual/CustomPackages.html

I can help if you want to go with this, as I'll probably have to fork soon and maintain my own package anyway.

**Comment by endel** [comment]
We finally provide both `.unitypackage` and UPM packages on the latest version! 🎉  (https://github.com/colyseus/colyseus-unity3d/pull/146)
