### ISSUE TITLE
Maybe Fossil.Apply Bug. (It could be a server's fossil_delta_1 problem.)

### ISSUE THREAD

**Issue by NakOh** [colyseus/colyseus-unity3d#109]
![image](https://user-images.githubusercontent.com/7420198/75092197-e0146d80-55b8-11ea-846b-98fda6da5503.png)

This code, I understood it as updating the changes from the previous information.

But 
I Use Colyseus version is 0.12.0 and client Colyseus Version is latest.

I have 

Game State 

    roundNo: number = 0;
    phase: SharedTypes.Phase = SharedTypes.Phase.Waiting;
    maxBetSeats: number = 0;
    turnSeatSort: number[] = [];
    nowTurnSeat: number = -1;
    useBonus: boolean           = false;
    players: { [id: string]: SharedTypes.Player } = {};
    betSeats: { [id: string]: SharedTypes.BetSeat } = {}; //is can empty.
    dealerSeat: SharedTypes.DealerSeat = {
        card: []
    };

If I send all state, client can read corret. ( I changed code.)

![image](https://user-images.githubusercontent.com/7420198/75092280-6a5cd180-55b9-11ea-8237-b4602acd10c4.png)
--FossileDeltaSerializer's State. 

![image](https://user-images.githubusercontent.com/7420198/75092241-236edc00-55b9-11ea-99ea-8b28479f4f6b.png)
---Server Code (Code I changed)--

![image](https://user-images.githubusercontent.com/7420198/75092248-29fd5380-55b9-11ea-88e6-4f19bf0d6b60.png)
--Client Code (Code I changed)--

it's work corretly.

But If i use originally code, it have trouble.

![image](https://user-images.githubusercontent.com/7420198/75092300-9aa47000-55b9-11ea-9f89-8b93a93c7ba6.png)

i don't know where is error;

I could have guessed that there was a problem with Fossil.Delta.Apply.

Or there is a problem with the server side of fossil_delta_1 on the server side.

**Comment by NakOh** [comment]
JsonSerializationException: Unexpected token readed 'EndOfStream' while 'BeginObject' is expected.
GameDevWare.Serialization.Serializers.ObjectSerializer.Deserialize (GameDevWare.Serialization.IJsonReader reader) (at Assets/Plugins/GameDevWare.Serialization/Serializers/ObjectSerializer.cs:69)
GameDevWare.Serialization.JsonReaderExtentions.ReadValue (GameDevWare.Serialization.IJsonReader reader, System.Type valueType, System.Boolean nextToken) (at Assets/Plugins/GameDevWare.Serialization/JsonReaderExtentions.cs:726)
GameDevWare.Serialization.Serializers.ObjectSerializer.DeserializeMembers (GameDevWare.Serialization.IJsonReader reader, GameDevWare.Serialization.IndexedDictionary`2[KeyT,ValueT] container, GameDevWare.Serialization.Serializers.ObjectSerializer& serializerOverride) (at Assets/Plugins/GameDevWare.Serialization/Serializers/ObjectSerializer.cs:191)
Rethrow as SerializationException: Failed to read value for member 'ready' of 'Object' type.
More detailed information in inner exception.
GameDevWare.Serialization.Serializers.ObjectSerializer.DeserializeMembers (GameDevWare.Serialization.IJsonReader reader, GameDevWare.Serialization.IndexedDictionary`2[KeyT,ValueT] container, GameDevWare.Serialization.Serializers.ObjectSerializer& serializerOverride) (at Assets/Plugins/GameDevWare.Serialization/Serializers/ObjectSerializer.cs:195)
GameDevWare.Serialization.Serializers.ObjectSerializer.Deserialize (GameDevWare.Serialization.IJsonReader reader) (at Assets/Plugins/GameDevWare.Serialization/Serializers/ObjectSerializer.cs:74)
GameDevWare.Serialization.JsonReaderExtentions.ReadValue (GameDevWare.Serialization.IJsonReader reader, System.Type valueType, System.Boolean nextToken) (at Assets/Plugins/GameDevWare.Serialization/JsonReaderExtentions.cs:726)
GameDevWare.Serialization.Serializers.DictionarySerializer.Deserialize (GameDevWare.Serialization.IJsonReader reader) (at Assets/Plugins/GameDevWare.Serialization/Serializers/DictionarySerializer.cs:139)
Rethrow as SerializationException: Failed to read 'Object' value for key 'bzSmxsAQv' in dictionary: Failed to read value for member 'ready' of 'Object' type.
More detailed information in inner exception.
More detailed information in inner exception.
GameDevWare.Serialization.Serializers.DictionarySerializer.Deserialize (GameDevWare.Serialization.IJsonReader reader) (at Assets/Plugins/GameDevWare.Serialization/Serializers/DictionarySerializer.cs:140)
GameDevWare.Serialization.JsonReaderExtentions.ReadValue (GameDevWare.Serialization.IJsonReader reader, System.Type valueType, System.Boolean nextToken) (at Assets/Plugins/GameDevWare.Serialization/JsonReaderExtentions.cs:726)
GameDevWare.Serialization.MsgPack.Deserialize (System.Type objectType, System.IO.Stream msgPackInput, GameDevWare.Serialization.SerializationContext context) (at Assets/Plugins/GameDevWare.Serialization/MsgPack.cs:79)
GameDevWare.Serialization.MsgPack.Deserialize[T] (System.IO.Stream msgPackInput, GameDevWare.Serialization.SerializationContext context) (at Assets/Plugins/GameDevWare.Serialization/MsgPack.cs:96)
GameDevWare.Serialization.MsgPack.Deserialize[T] (System.IO.Stream msgPackInput) (at Assets/Plugins/GameDevWare.Serialization/MsgPack.cs:84)
Colyseus.FossilDeltaSerializer.Patch (System.Byte[] bytes, System.Int32 offset) (at Assets/Plugins/Colyseus/Serializer/FossilDeltaSerializer.cs:24)
Colyseus.Room`1[T].Patch (System.Byte[] delta, System.Int32 offset) (at Assets/Plugins/Colyseus/Room.cs:179)
Colyseus.Room`1+<ParseMessage>d__33[T].MoveNext () (at Assets/Plugins/Colyseus/Room.cs:168)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <437ba245d8404784b9fbab9b439ac908>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <94c5f4c38cdc42d2b006f8badef04394>:0)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()


Error log in Unity.

**Comment by NakOh** [comment]
![image](https://user-images.githubusercontent.com/7420198/75092393-63828e80-55ba-11ea-9428-ed70804e62f6.png)

ObjectSerializer. But token is EndOfStream.

**Comment by endel** [comment]
Hi @NakOh, wouldn't it be easier to use the schema serializer instead? It performs much better than Fossil Delta.

(This bug must've slipped on 0.12.x due to the [protocol changes](https://github.com/colyseus/colyseus/releases/tag/0.12.0))

**Comment by NakOh** [comment]
@endel  Yeah. I Know that.

Already new projects are using the schema serializer.

But This project was built before the schema serializer.

And the game must be released soon.

So I need to modify it to work in its current state.

If you can provide technical support, I will pay for it.

**Comment by endel** [comment]
Oh, I see. I've just sent you an email to the address listed on your GitHub profile.

**Comment by endel** [comment]
I believe this issue has been fixed on latest version https://github.com/colyseus/colyseus-unity3d/blob/master/Assets/Plugins/Colyseus/Serializer/FossilDeltaSerializer.cs

Please let me know if you still have any problems with it!
