### ISSUE TITLE
https support for HTML5 builds

### ISSUE THREAD

**Issue by Wenish** [colyseus/colyseus-unity3d#111]
We should fix those lines:
```csharp
uriBuilder.Scheme = uriBuilder.Scheme.Replace("ws", "http"); // FIXME: replacing "ws" with "http" is too hacky!
```

**Comment by endel** [comment]
Hi @Wenish, if you provide `"wss://"` in your endpoint, it should be properly replaced with `"https://"`. 

I agree that for HTML5 builds, it would be nice to auto-detect if the page is under `https` to automatically use wss/https in the endpoints.

**Comment by Wenish** [comment]
should do the job for now
