### ISSUE TITLE
Release v0.13.2 won't compile due to an extra brace in ArrayUtil.cs

### ISSUE THREAD

**Issue by rnd256** [colyseus/colyseus-unity3d#124]
This was fixed 19 days ago by https://github.com/colyseus/colyseus-unity3d/commit/b61fb4936cb0be7679e6352b824bc15f2a1eaaef, but should be included in a new release.

**Comment by endel** [comment]
Thanks for noticing @rnd256, just released it here https://github.com/colyseus/colyseus-unity3d/releases/tag/0.13.3
