### ISSUE TITLE
Race condition with `onAuth()` rejection

### ISSUE THREAD

**Issue by rnd256** [colyseus/colyseus-unity3d#125]
If the Colyseus server's room throws a custom application error or returns false from `onAuth()`, the Colyseus Unity client sometimes hangs and gets no response.

eg. The below Unity client snippet sometimes never prints either of `"Joined room successfully"` or `"Error joining room"`.

```cs
Client colyseusClient = new Client(COLYSEUS_URL);
Room<GameState> newColyseusRoom;
try {
  Debug.Log("Joining room...");
  newColyseusRoom = await colyseusClient.JoinOrCreate<GameState>("GameRoom", options);
  Debug.Log("Joined room successfully");
} catch (Exception e) {
  Debug.Log("Error joining room");
}
```

With the server snippet:

```ts
export default class GameRoom extends Room<GameState> {
  onAuth(_client: Client, _options: any): Promise<boolean> {
    return false;
  }
}
```

Colyseus Unity client version: 0.13.2  
Colyseus Unity server version: 0.13.7

Possibly related:
* https://github.com/colyseus/colyseus-unity3d/pull/118
* https://github.com/colyseus/colyseus-unity3d/pull/119

**Comment by rnd256** [comment]
@AJ92 or @chsqn, can you comment on if you think your PRs are related to this?

**Comment by chsqn** [comment]
Could you make sure the issue still occurs if server alway return false at OnAuth()?
> ```ts
> export default class GameRoom extends Room<GameState> {
>   onAuth(_client: Client, _options: any): Promise<boolean> {
>     return false;
>   }
> }
> ```

**Comment by AJ92** [comment]
> @AJ92 or @chsqn, can you comment on if you think your PRs are related to this?

could be the case that the PRs fix this

**Comment by rnd256** [comment]
I just tested it, and https://github.com/colyseus/colyseus-unity3d/pull/119 fixes this issue (see https://github.com/rnd256/minimal-colyseus/tree/onauth-rejection-race-condition-patched).

I hope we can push that fix through.

**Comment by endel** [comment]
Thanks for taking the time to check and create the reproduction repository @rnd256, I did merged #119, not sure this will introduce delays as mentioned by @AJ92 on #118 though, as we currently don't have unit testing for this type of thing on the client.

I'd appreciate if you can already use 0.14 alpha, and report back if you have any issues: https://github.com/colyseus/colyseus-unity3d/releases/tag/0.14.0-alpha.1
I'm already using the javascript client for 0.14 on two projects and it seems stable so far.

Cheers!

**Comment by AJ92** [comment]
> 
> 
> Thanks for taking the time to check and create the reproduction repository @rnd256, I did merged #119, not sure this will introduce delays as mentioned by @AJ92 on #118 though, as we currently don't have unit testing for this type of thing on the client.
> 
> I'd appreciate if you can already use 0.14 alpha, and report back if you have any issues: https://github.com/colyseus/colyseus-unity3d/releases/tag/0.14.0-alpha.1
> I'm already using the javascript client for 0.14 on two projects and it seems stable so far.
> 
> Cheers!

I guess both solutions work more or less the same way, one ( #119 ) introduces new code, but changes less of existing code, the other solution ( #118 ) removes code but changes a bit more of existing code.

**Comment by rnd256** [comment]
FYI I didn't mean to indicate that I thought one of #118 and #119 was better than the other. #119 just happened to be the one I tested.

@endel unfortunately I'm not well-equipped to measure latency either (my game is not particularly latency-sensitive). Or were you just asking that I verify that the alpha branch fixes this bug?

**Comment by chsqn** [comment]
#119 refers to [Unity3dAsyncAwaitUtil](https://github.com/svermeulen/Unity3dAsyncAwaitUtil). Its [blog](http://www.stevevermeulen.com/index.php/2017/09/using-async-await-in-unity3d-2017/) mentions that
```
our async methods will be run on the main unity thread by default.
In non-unity C# applications, async methods are often automatically run on separate threads
```
The following code also displays the same thread id.
```
using UnityEngine;
using System.Threading;
using System.Threading.Tasks;

public class foobar : MonoBehaviour
{
    void printout_threadid()
    {
        Debug.Log(Thread.CurrentThread.GetHashCode().ToString());
    }

    async void Start()
    {
        printout_threadid();
        int result = await GetCount();
    }

    private async Task<int> GetCount()
    {
        printout_threadid();
        return await Task.FromResult<int>(1);
    }
}
```
This means that #118 runs everything in the main unity thread.
If it is so, we can just comment out the line as below to fix the threading error.
https://github.com/colyseus/colyseus-unity3d/blob/cafff755225ede69e88144930068da08c1e6613f/Assets/Plugins/WebSocket/WebSocket.cs#L493

**Comment by rnd256** [comment]
Friendly ping

**Comment by endel** [comment]
Hi @rnd256, is this still an issue for you using the code on branch `master`?

**Comment by rnd256** [comment]
@endel I've verified that the current master branch resolves this issue:
https://github.com/rnd256/minimal-colyseus/tree/onauth-rejection-race-condition-2020-10-11-master-branch

(I can't comment about performance though, which is something you were worried about before)

**Comment by endel** [comment]
Thanks for confirming, let's close this for now, then :)
