### ISSUE TITLE
0.14.5 Client: ColyseusClient.JoinOrCreate task runs indefinitely despite successful room creation

### ISSUE THREAD

**Issue by tonygiang** [colyseus/colyseus-unity3d#148]
On the 0.14.5 Unity client, the task returned by `ColyseusClient.JoinOrCreate` will never finish running even though I can confirm that a connection was made with a Colyseus server running version 0.14.13. Notably: creation of a room was successful, Unity client appeared to receive room information in the Console, and that's where it hangs, it did not succeed in joining said room.
![2021-05-10 18_19_29-Window](https://user-images.githubusercontent.com/7429894/117651676-6b791f00-b1bc-11eb-8e86-a94fb03190a1.png)

Upon inspecting the join task, its `Status` field always reads `WaitingForActivation`.

**Comment by mitchLucid** [comment]
@tonygiang please let me know if the issue persists, I'm receiving "RanToCompletion" status on the tasks now after the last pull request

**Comment by tonygiang** [comment]
Appears to work on initial testing.
