### ISSUE TITLE
possibility to cast the state to a specific data type

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus-unity3d#24]
Currently, the only way to cast the state to a specific data type is by de-serializing it **again** in the `OnUpdate` action:

```
room.OnUpdate += OnRoomUpdate;

   private void OnRoomUpdate(object sender, RoomUpdateEventArgs update)
    {
            var outputStream = new System.IO.MemoryStream();
            MsgPack.Serialize(update.state, outputStream);
            outputStream.Position = 0;
            this.gameRoom = MsgPack.Deserialize<GameRoom>(outputStream);
```

It would be great if the client allows to provide a data-type when joining the room - and use it for de-serializing automatically - for example:

```
client.Join<GameRoom>("game_room");
```

(Thanks for proposing @derwish-pro)

**Comment by shophk** [comment]
Hi I try implementing this myself. Would you please take a look?
I have uploaded the code to this https://github.com/shophk/try_colyseus.git

If it is something like this. My question is, how do I send updated data from the server to put into my "GameRoom". I added a class GameRoom with one string variable RoomName, how to assign a RoomName of the GameRoom from the sever?  

The code now the GameRoom is completely empty.

**Comment by endel** [comment]
This is currently possible with the new schema serializer, states have a strict type defined: https://docs.colyseus.io/state/schema/#client-side-schema-generation
