### ISSUE TITLE
InvalidCastException Room.cs

### ISSUE THREAD

**Issue by aedbrault** [colyseus/colyseus-unity3d#48]
Hi , i have a new bug , its full random , i cant reproduce by my self
`InvalidCastException: Cannot cast from source type to destination type.
Colyseus.Room.ParseMessage (System.Byte[] recv) (at Assets/Plugins/Colyseus/Room.cs:153)
Colyseus.Room.Recv () (at Assets/Plugins/Colyseus/Room.cs:83)
Colyseus.Client.Recv () (at Assets/Plugins/Colyseus/Client.cs:90)
WsHandler+<Start>c__Iterator1.MoveNext () (at Assets/Scripts/Network/Websockets/WsHandler.cs:144)`
On Line 153 Room.cs : 
`				this.sessionId = (string) message [1];`

**Comment by aedbrault** [comment]
Same issue here , i up the post

**Comment by AJ92** [comment]
i think i have a similar issue :)
when node sends a change of type double/float for example and the value is 0.0, then on unity's side it is an integer all of a sudden so the convertToDouble function throws errors. So i assume your value might be some kind of other type.

**Comment by endel** [comment]
This shouldn't happen anymore using the new schema serializer: https://docs.colyseus.io/state/schema/
