### ISSUE TITLE
GetAvailableRooms doesn't deserialise metadata correctly

### ISSUE THREAD

**Issue by gioragutt** [colyseus/colyseus-unity3d#51]
When I set my room metadata, even at `Client.cs:220` you can see that `metadata` is null in the received object.

```typescript
  onInit(options: any): void {
    this.setState(this.initialPlayerState());
    this.maxClients = options.maxClients || MAX_PLAYERS_IN_ROOM;
    this.setMetadata({
      mode: options.mode || '',
      name: options.name || `Room ${this.roomId}`,
    });
  }
```

I tried `JSON.stringify`ing the metadata object, still don't get a `string` on the client side.

**Comment by endel** [comment]
As of `0.11.4`, it is possible to retrieve the metadata from the client-side by defining a custom `RoomAvailable` + `Metadata` types.

**Example:**

```csharp
[Serializable]
class Metadata
{
	public string mode;
	public string name;
}

[Serializable]
class CustomRoomAvailable : RoomAvailable
{
	public Metadata metadata;
}
```

```csharp
var roomsAvailable = await client.GetAvailableRooms<CustomRoomAvailable>(roomName);

for (var i = 0; i < roomsAvailable.Length; i++)
{
    // getting metadata
    Debug.Log("metadata.mode: " + roomsAvailable[i].metadata.mode);
    Debug.Log("metadata.name: " + roomsAvailable[i].metadata.name);
}
```

---

The metadata comes from a JSON response from the server. Unfortunately, the built-in `JsonUtility` from Unity has limitations regarding the usage of generic types, making it necessary to create a new type having its own hardcoded `Metadata` type defined on it. ([here's the method to decode the JSON response](https://github.com/colyseus/colyseus-unity3d/blob/287c6c561d1141ad1079b0cc5509df5b2b6affa5/Assets/Plugins/Colyseus/Client.cs#L138))

If you think the API can be improved please don't hesitate to share your thoughts.
