### ISSUE TITLE
v 0.10 : how to know which property change in schema ?

### ISSUE THREAD

**Issue by etherny** [colyseus/colyseus-unity3d#57]
Hello, in the unity exemple, specificly in OnPlayerMove method, could i know which field changed ?
If only x changed or both.
In a class with more properties it can be usefull.

Thank you.

**Comment by endel** [comment]
hey @etherny, check C# tab in the docs here: https://docs.colyseus.io/state/schema/#onchange-changes-datachange

**Comment by etherny** [comment]
I will try this. thank you.
