### ISSUE TITLE
v 0.10 : Nested schemas

### ISSUE THREAD

**Issue by etherny** [colyseus/colyseus-unity3d#58]
Hi, i tried to externalize X and Y in unity exemple, in a Position schema and look for changes in this new Schema and X increment in JS onMessage method.
I regenerated the c# classes, change the code accordly and register an handler on the position in OnPlayerAdd method like this : 

`item.Value.position.OnChange += OnPositionChange;`

I do not receive any event from position change. Server debug changes on Position.

Here the source code.

[colyseus-unity3d.zip](https://github.com/colyseus/colyseus-unity3d/files/3024129/colyseus-unity3d.zip)

Thank you for your help.

**Comment by endel** [comment]
@etherny are you using latest version of `@colyseus/schema`? the last one is `0.4.6`

**Comment by etherny** [comment]
just clone the unity exemple repo, i will check.

**Comment by endel** [comment]
Try removing `package-lock.json`, and installing the dependencies again. I think it was forcing a previous version, sorry about that

**Comment by etherny** [comment]
it works ! thank you.
