### ISSUE TITLE
Coroutine or thread

### ISSUE THREAD

**Issue by etherny** [colyseus/colyseus-unity3d#59]
Hello, i the previous version (before 0.10) i met some performances issue due to socker reading in coroutine then i move this in thread with queue system to process events.
Do you think than the v0.10 serialization will resolve this coroutine perfomance issue ?

**Comment by endel** [comment]
I'm not too familiar with these concepts in Unity, I'd appreciate if you could guide me about this. 

What I can tell is that the performance now is supposed to be much higher. Previously the whole state needed to be decoded at each patch, now it decodes only what's really necessary.

**Comment by etherny** [comment]
I will do my migration to v0.10 in next days.
If the performance issue always there, i will come back to you about thread proposal.
