### ISSUE TITLE
v0.10 : c# file generation and extends

### ISSUE THREAD

**Issue by etherny** [colyseus/colyseus-unity3d#60]
Hi, i have a class A extending schema and another class B extending the A at generation fields with @type decorator in A are not present in class B, and c# class B extends schema and not class A.
Any solution for this ?

Thank you.

**Comment by endel** [comment]
@etherny this has been fixed on `@colyseus/schema@0.4.9`. I'm going to check your suggestion sent by email soon, thanks a lot @etherny!
