### ISSUE TITLE
v0.10 : KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by etherny** [colyseus/colyseus-unity3d#61]
I receive a key not found at https://github.com/colyseus/colyseus-unity3d/blob/master/Assets/Plugins/Colyseus/Serializer/Schema/Schema.cs#L335

I added logs to this file : 
Each fields created at https://github.com/colyseus/colyseus-unity3d/blob/master/Assets/Plugins/Colyseus/Serializer/Schema/Schema.cs#L295

And log 335 line too.

Schema try to get an index not listed in 275 lines logs.

Try to get index 50 in a schema with 23 fields detected in constructor.

Fields generated by last version of c# generator (original version)

Version : 
colyseus : 0.10.2
schema : 0.4.9

**Comment by etherny** [comment]
@endel hi, it's not possible to share the project, but if you have a little time we can try do debug it remotly ?
You have my email, send me your availability.
I m blocked.

**Comment by endel** [comment]
@etherny sent you an email. It might be a misusage of the schemas on the server-side, or really a bug in the C# decoder. I'd like to take a look. Cheers

**Comment by etherny** [comment]
here the Schema backend structure


Le lun. 1 avr. 2019, à 15 h 52, Endel Dreyer <notifications@github.com> a
écrit :

**Comment by etherny** [comment]
@endel hi, i found the problem.
I m using a custom UUID generation and the method do not return a supported type.
Now i m using generateId from Colyseus, and it works.
Perhaps rise an exception server side when an unsupported value type fill a field.

**Comment by endel** [comment]
@etherny phew, glad you figured it out. Yeah definitely need to check the types on runtime. Thanks a lot!
