### ISSUE TITLE
v0.10 : Strange behaviour in nested Schemas

### ISSUE THREAD

**Issue by etherny** [colyseus/colyseus-unity3d#62]
Hi, i using 3 level nested structure : 
Player --> Camp --> Position
Where camp is just a name/position
and Position is a vector of 3 floats

At the first player connection, all works fine.
But if i leave the room (it disposed : normal behaviour), and join a new one roomthen camp position is wrong (0,0,0).

If a restart the server, the first connection give me the good one camp position, and others connections send me a camp with 0,0,0 vector.

Note : i do not use any cache system.
All room state recreated from scratch

**Comment by etherny** [comment]
```
export class Player extends Schema {
    @type(Camp) camp : Camp;   
    constructor(client: Client, userId: string, camp: Camp, ) {
        super();
        this.camp = camp;
    }
```
```
export class Camp extends Schema{

    @type("string") name : string;
    @type(Point) home : Point;

    constructor(name : string, home : Point) {
        super();
        this.name = name;
        this.home = home;
    }
}
```
```
export class Point extends Schema{
    @type("float32") x : number;
    @type("float32") y : number;
    @type("float32") z : number;

    constructor(x : number,
        y : number,
        z : number){
            super();
            this.x = x;
            this.y = y;
            this.z = z;
    }
```

**Comment by etherny** [comment]
I m reading player.camp.home in this delegate method : 
room.State.players.OnAdd += playerManager.OnAddPlayer

**Comment by etherny** [comment]
I m using point Schema in other nested places and it works fine.

**Comment by endel** [comment]
Thanks a lot for your inputs @etherny, I'm going to check this tomorrow (already quite late for me here)

BTW, I've already published a new version of `@colyseus/schema` that validates invalid data on strings and numbers.

**Comment by etherny** [comment]
Perhaps a static or cached data in Schema, i do not understand why after server restart then point have good data. Room disposed as expected after unity quit.

**Comment by endel** [comment]
hey @etherny, I think this problem comes from expecting that `OnChange` is going to be called right upon its registration. The thing is that it is called only after a change has been made. The correct value may already be accessible in the state, but the callback wasn't triggered.

Let me know if that's the case for you. I'd like to provide some API for triggering existing data as changes, just not sure how to expose them yet.

**Comment by etherny** [comment]
I m reading directly the value of player.camp.home after OnAdd player in state.

**Comment by endel** [comment]
hi @etherny, I've tried to reproduce this issue, do you mind checking the [branch `issue-64`](https://github.com/colyseus/colyseus-unity3d/tree/issue-64) when you have some time?

I've basically modified the sample project to include the same structures as you described here.

To test, you can:
- start the server, run the client
- click on "Connect"
- click on "Join Room"
- click a few times on "Send Message" (will change the block position)
- click "Leave Room"
- click "Re-join Room"

the positions look fine here for me. maybe your Schema structure is a bit different? cheers!

**Comment by endel** [comment]
The method to update the cube position is here: https://github.com/colyseus/colyseus-unity3d/blob/issue-64/Assets/ColyseusClient.cs#L164-L174

**Comment by etherny** [comment]
i will check the code and compare it to mine, the only one different user action than mine, is the leave/rejoin instead of restart completly the game.

**Comment by etherny** [comment]
@endel hi, i tested your branch and all works (even after restart of the unity scene), i will check my code to compare.
Thank you again.
Will back to you tomorrow.

**Comment by etherny** [comment]
@endel i found !

Add a const camp in you project, and use it in player : 

```
const BLUE_CAMP = new Camp("BLUE", new Position(0, 0.5, 1));
......
@type(Camp) camp: Camp = BLUE_CAMP;
```

In unity join, leave and join again (not re-join)

I added a debug log in OnPlayerAdd c# method too : 
`
Debug.Log("Initial camp position x: " + item.Value.camp.position.x + ", y: " + item.Value.camp.position.y + ", z: " + item.Value.camp.position.z);`

I don't know why, but the first time to camp position is good, and the second join receive a position = (0,0,0)

Solution (work around, i don't like that) : I will make a copy of constant camp before use it in player.

**Comment by endel** [comment]
@etherny I see, glad you figured it out. Not sure how to express this in the docs, but you shouldn't really re-use instances to be encoded more than once in the schema. 

Each `Schema` object has an internal list of changes, so if anything has changed in your constant `BLUE_CAMP`, it won't be serialized in the next patch.

**Comment by etherny** [comment]
Is it possible to have a copy or clone method on Schema ? 
It could be a good practice to use constants.

If not, please add documentation warning around Schema as constant.

**Comment by endel** [comment]
Sounds good! I've added a `.clone()` method on `@colyseus/schema@0.4.18`. Thanks @etherny
