### ISSUE TITLE
don‘t work GetAvailableRooms in example scene？

### ISSUE THREAD

**Issue by PainterPuppets** [colyseus/colyseus-unity3d#66]
i have try add GetAvailableRooms to example scene, but i get this error ,can someone help me ?
![image](https://user-images.githubusercontent.com/22258327/56451723-ba4a8680-635f-11e9-9e57-e450a20fd6ff.png)

this is my code 
![image](https://user-images.githubusercontent.com/22258327/56451761-e0702680-635f-11e9-9e14-ecff6d140841.png)

**Comment by PainterPuppets** [comment]
i perhaps understand this bug reson, this is because RoomAvailable's maxClients type is unit , but this default value is Infinity.
i dont think this reasonable
![image](https://user-images.githubusercontent.com/22258327/56452474-ca646500-6363-11e9-8593-b2d5b4f63da1.png)

**Comment by endel** [comment]
I've added a workaroud for this (https://github.com/colyseus/colyseus-unity3d/commit/2bfc3f61a894bb79580bccb22df528441ef88499). Thanks for reporting!
