### ISSUE TITLE
Room.OnStateChange possibly has a behavior you might not have intended in the first place

### ISSUE THREAD

**Issue by ChristianIvicevic** [colyseus/colyseus-unity3d#67]
This time I stumbled upon some unexpected behavior in the client library for Unity. In my sample I want to store the previous X states that the server returns to the client in order to interpolate between states. Hence I wrote the following (simplified) handler:

```csharp
room.OnStateChange += OnStateChangeHandler;

// ...

private void OnStateChangeHandler(object sender, StateChangeEventArgs<TestRoomSchema> e)
{
    snapshotQueue.Enqueue(e.State);
    // Dequeue some older states if older than X updates
    // ...
}
```
It turns out that this handler it not getting a copy of each new state but the reference to the current state **every single time**. As a consequence my queue will increase in size but hold the very same reference across each element instead of actualy copies (snapshots) of previous states.

1. I'd like to see an update wherein the handler would in fact return copies instead of the same reference to `Room.State`.
2. Furthermore I noticed, similar to the server variant of the Schema class, that one is able to call the methods of the Schema class via `e.State.Decode`, `e.State.TriggerAll`, `e.State.OnChange` and `e.State.OnRemove`.

**Comment by endel** [comment]
Hey @ChristianIvicevic, it is actually intended to have a reference of the state and not the full copy of it. The FossilDelta serializer actually will produce a full copy of the state, and that has proven to be an overhead to the client. 

I'd recommend using `OnChange +=`, and using the `change.Value` / `change.PreviousValue` available there. (https://docs.colyseus.io/state/schema/#onchange-changes-datachange)

If you really need a copy of the whole state, you can manually "clone" the structure by instantiating new references and assigning current values to them.

> Furthermore I noticed, similar to the server variant of the Schema class, that one is able to call the methods of the Schema class via e.State.Decode, e.State.TriggerAll, e.State.OnChange and e.State.OnRemove.

Thanks for letting me know, only the `Decode` method shouldn't be called by the user, I'll see what I can do. `TriggerAll`, `OnChange` and `OnRemove` are correct to be public!

Cheers! Happy Easter! 🐰

**Comment by ChristianIvicevic** [comment]
Thank you for clarifying this, closing this issue.
