### ISSUE TITLE
CompareTypes function does not work for ArraySchema of Primitive types like uint8...

### ISSUE THREAD

**Issue by napbla** [colyseus/colyseus-unity3d#71]
Environment: unity 2018.3.12f1, .Net 4x
SchemaSerialize.cs

The bug is due to reflectionField.type is 'array:uint8' while typedField.FieldType is 'array' so it can not match schemaType. Although they are the same. Hence it will output "Local schema mismatch from server. Use \"schema-codegen\" to generate up-to-date local definitions."

**Comment by endel** [comment]
@napbla I've just created a pull-request that's supposed to fix this:
- https://github.com/colyseus/colyseus-unity3d/pull/70
- https://github.com/colyseus/schema/pull/21

**Comment by endel** [comment]
This has been fixed on [0.10.5](https://github.com/colyseus/colyseus-unity3d/releases/tag/0.10.5)! 🎉
