### ISSUE TITLE
List<object> warning in Compare.cs

### ISSUE THREAD

**Issue by bartwttewaall** [colyseus/colyseus-unity3d#72]
Plugins/Colyseus/StateListener/Compare.cs(60,8): warning CS0184: The given expression is never of the provided ('List<object>') type

I've replaced "obj is List<object>" on line 60 with a new method "IsList (obj)" which solves the warning. Haven't tested and no PR.. Sorry, I'm on a deadline ;)

```
protected static bool IsList (object o) {
  if (o == null) return false;
  return o is IList &&
    o.GetType ().IsGenericType &&
    o.GetType ().GetGenericTypeDefinition ().IsAssignableFrom (typeof (List<>));
}
```

**Comment by endel** [comment]
This has been fixed by @Wenish on https://github.com/colyseus/colyseus-unity3d/pull/78, thanks @bartwttewaall
