### ISSUE TITLE
use System.Net.WebSockets instead of WebSocketSharp dependency

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus-unity3d#74]
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets?view=netframework-4.8

**Comment by chsqn** [comment]
Is this client used for real games?
I found that OnOpen and OnClose are in different threads.
I check out websocket-sharp.dll with ILSpy.
ConnectAsync() uses BeginInvoke()/EndInvoke() as below:
```Func<bool> connector = connect;
connector.BeginInvoke(delegate(IAsyncResult ar)
{
    if (connector.BeginInvoke(delegate(IAsyncResult ar)
    {
        if (connector.EndInvoke(ar))
        {
            open();
        }
    }
}, null);
```
It seems like all events occur in different threads.
I check out the thread id with
```
System.Threading.Thread.CurrentThread.ManagedThreadID
```
And even I use Connect instead ConnectAsync, OnMessage is still not in the main thread.
I also look at the examples on [websocket-sharp](https://github.com/sta/websocket-sharp).
All messages are queued with in critical sections.
```
public void Notify (NotificationMessage message)
{
    lock (_sync) {
        if (_enabled)
            _queue.Enqueue (message);
    }
}
```
But code at here just uses
```
Queue<byte[]> m_Messages = new Queue<byte[]>();
```
As I know, Queue<> is not thread safe.

**Comment by endel** [comment]
hi @chsqn, I've made a big pull-request to remove WebSocketSharp completely today, please feel free to give some feedback there! https://github.com/colyseus/colyseus-unity3d/pull/83
