### ISSUE TITLE
Bug: replacing "ws" with "http" in uri modifies access token

### ISSUE THREAD

**Issue by MateusMendesSantana** [colyseus/colyseus-unity3d#81]
`if (HasToken) query["token"] = Token;`
Auth.cs, line 249
`// FIXME: replacing "ws" with "http" is too hacky!
req.url = uriBuilder.Uri.ToString().Replace("ws", "http");`

client token:

> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDM5ZWZjODFlMzA5M2UxYzRlMDJjMjkiLCJpYXQiOjE1NjQyMzQ4MjF9.y5FVhZcIQiESp1rIHKCWx3WC10wxnWwGCGh8plX49**ws**

has been replaced by:

> eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZDM5ZWZjODFlMzA5M2UxYzRlMDJjMjkiLCJpYXQiOjE1NjQyMzQ4MjF9.y5FVhZcIQiESp1rIHKCWx3WC10wxnWwGCGh8plX49**http**

**Comment by endel** [comment]
Really well-observed @MateusMendesSantana, I think we can use a `ReplaceFirst` instead to prevent this from happening, like:

```csharp
    public static string ReplaceFirst(this string text, string search, string replace)
    {
      int pos = text.IndexOf(search);
      if (pos < 0)
      {
        return text;
      }
      return text.Substring(0, pos) + replace + text.Substring(pos + search.Length);
    }
```

**Comment by MateusMendesSantana** [comment]
Thank you @endel. Could be, I just did it:
`req.url = uriBuilder.Uri.ToString().Replace("ws://", "http://");`
I think the right thing would be to fragment the URI, separate the protocol, address and port. Mount the URI on request only

**Comment by endel** [comment]
@MateusMendesSantana sounds better indeed! I'd gladly merge if you don't mind sending a PR <3
