### ISSUE TITLE
Upgrade to 2019.2.0f1 : 'HttpUtility'

### ISSUE THREAD

**Issue by etherny** [colyseus/colyseus-unity3d#82]
Upgrade to new unity version cause Assets\Plugins\Colyseus\Auth.cs(109,16): error CS0103: The name 'HttpUtility' does not exist in the current context

**Comment by endel** [comment]
Thanks @etherny, I've checked and `HttpUtility` is only used on `colyseus-unity3d` to generate query strings:

```
var query = HttpUtility.ParseQueryString(string.Empty);
```

The `HttpUtility` class returns a type of `NameValueCollection`, which implements an overriden `ToString()` method that turns the `NameValueCollection` into a query string. (see [mono source code](https://github.com/mono/mono/blob/e70ac8c6ae7ff3f03517be90babb8f7c25d18b97/mcs/class/System.Web/System.Web/HttpUtility.cs#L49-L65))

We'd basically need another approach to do this without relying on `HttpUtility`. Do you have any suggestion?

**Comment by etherny** [comment]
Using WebUtility equivalent ?
