### ISSUE TITLE
Proposal: Allow to send data to the room using a custom Serializable instance

### ISSUE THREAD

**Issue by endel** [colyseus/colyseus-unity3d#89]
It would be nice to allow using custom Serializable structures to send data to the room. 

**Example:**

```csharp
[Serializable]
public class InputData
{
    public bool left;
    public bool right;
    public bool top;
    public bool bottom;
}

// e.g. catch user inputs
var input = new InputData();
input.left = true;
input.top = true;

// send the serializable structure
room.Send(input)
```

**Comment by ADustyOldMuffin** [comment]
I'd be interested in working on this if it's still open.

**Comment by endel** [comment]
Hi @ADustyOldMuffin, nice. Feel free to send a PR 🤗

**Comment by endel** [comment]
Implemented here https://github.com/colyseus/colyseus-unity3d/commit/1954d98aa47caaec2b17d40e6fed2408a189ebb4#diff-71c9fc0505f323e7aa448bcafd028c94R31
